### ISSUE TITLE
Improve size of library

### ISSUE THREAD

**Issue by arackaf** [rse/graphql-query-compress#5]
Hi!  I'm making great use of your library over here https://github.com/arackaf/micro-graphql-react  —
 Great work, and thank you!

It seems the size of your graphql-query-compress utility is being inflated a bit since it's pulling in a *bunch* of stuff from tokenizr which isn't actually used, since tokenizr just exports a single class.  Would you be open to a PR to improve this?  I imagine there's two straightforward ways the library size could be improved here: 

1) inline a subset of tokenizr into graphql-query-compress, using only what's needed.

2) probably the more sensible option imo, break tokenizr into two classes, a base class, containing only the basic things which this library uses, and then a second class inheriting from that, adding everything else. Tokenizr would of course export default the latter, so this would not be a breaking change. But then also add a named export of the new base class, which graphql-query-compress could import, and then webpack or Rollup should be able to tree shake everything else.

Would you be open to a PR doing either of those?

**Comment by rse** [comment]
Well, what particular "bunch of stuff" do you see in Tokenizr which is NOT used? Tokenizr is just 31KB of source code and 19KB of compressed source code. I do not see "large" parts of Tokenizr which could be factored out and not used by any user of the Tokenizr API class. Currently, the resulting graphql-query-compress is 20KB in size with 19KB of it is the embedded Tokenizr, of course. But even if one would leave out a little bit of unused code we are speaking perhaps about 1-2KB of code which could be left out. I'm not sure whether a decrease from 20K to 18KB for graphql-query-compress deserves the effort and resulting packaging complexity in a splitted tokenizr library...

**Comment by arackaf** [comment]
If the difference is that small then I agree it wouldn't be worth it. Let me take a closer look and see how big the difference would be

**Comment by arackaf** [comment]
Hi!  It looks like it'll save 5.7KB minified off of your library.  I've got a proof of concept whipped up here:

https://github.com/arackaf/tokenizr/pull/1

This is JUST a proof of concept to prove to myself that it'd work.  The magic is entirely in src/tokenizrBasic.js. That's a base class for Tokenizr, which the standard default export would extend from.

If you're ok with it, I could start over and send you a new PR with ***just*** that file split out from src/tokenizr-5-tokenizer.js, with literally *no* other changes (no webpack added, no new entry points, and I won't jack up your formatting with Prettier this time).  And I'll name the file whatever you want.

With that change in place, I could reduce the size of graphql-query-compress by over a fourth by just changing this line 

```javascript
import Tokenizr from "tokenizr"
```

to this

```javascript
import Tokenizr from "tokenizr/src/tokenizrBasic"; //or whatever you want me to call it
```

are you cool with that?

**Comment by rse** [comment]
Thanks for your efforts. I've looked at your PoC and even invested two hours into splitting Tokenizr into 4 API extension levels according to your basic idea:

```
-rw-r--r--  1 rse  rse   2413 Feb 11 11:36 tokenizr-1-excerpt.js
-rw-r--r--  1 rse  rse   2016 Feb 11 11:36 tokenizr-2-token.js
-rw-r--r--  1 rse  rse   2181 Feb 11 11:36 tokenizr-3-error.js
-rw-r--r--  1 rse  rse   4000 Feb 11 14:08 tokenizr-4-context.js
-rw-r--r--  1 rse  rse  12429 Mar  3 10:12 tokenizr-5-api-basic.js
-rw-r--r--  1 rse  rse   4281 Mar  3 10:14 tokenizr-6-api-state.js
-rw-r--r--  1 rse  rse   3477 Mar  3 10:17 tokenizr-7-api-trans.js
-rw-r--r--  1 rse  rse   3313 Mar  3 10:16 tokenizr-8-api-ultra.js
-rw-r--r--  1 rse  rse   1289 Mar  3 10:13 tokenizr.js
```

The original output size was 19.7KB...

```
-rw-r--r--  1 rse  wheel  19735 Feb 11 14:11 tokenizr.js
```
...and if one would pack just from tokenizr-5-api-basic instead of tokenizr-8-api-ultra, one would get about 15.9KB:

```
-rw-r--r--  1 rse  rse  15926 Mar  3 10:10 tokenizr.js
```

BUT: When packaging now from tokenizr-8-api-ultra, instead of the original 19.7KB, we now get 24.5KB:

```
-rw-r--r--  1 rse  rse  24488 Mar  3 10:19 tokenizr.js
```

So, nice optimization attempt, but wrong direction. It is not worth the efforts. Just to be able to gain 4 KB is not worth having to deal with multiple API extension levels and an effective default size increase by 5KB! So, I've dropped this attempt entirely again. Sorry, I'll not investigate further in this direction as it is the wrong direction from my point of view.

Nevertheless, I was able to reduce Tokenizr by to an effective size of 14.8KB:

```
-rw-r--r--  1 rse  rse  14894 Mar  3 11:14 tokenizr.js
```

But not by primarily changing the code, but by avoiding the Browserify overheads multiple "import" statements cause. This is also the reason why after your code splitting approach the ultra API even grow in size. With this reduced Tokenizr, the size of graphql-query-compress at lest shrinked by 2.6KB:

```
-rw-r--r--  1 rse  rse  20752 Feb 25 15:04 graphql-query-compress.browser.js
-rw-r--r--  1 rse  rse  18154 Mar  3 11:16 graphql-query-compress.browser.js
```
Voila! This has to be sufficient. If still not, please write a hand-coded variant which avoids a full-featured tokenizer like Tokenizr at all. Thanks.

**Comment by arackaf** [comment]
Hi! Thanks for your effort here! I feel kind of bad that you spent the effort inlining the entire module. I didn't bring up Browserify inefficiencies, but it was on my mind. Is there a reason you're not using Rollup? I'd be happy to split your code back up into nicely separated files, and then switch you to Rollup for your bundling. Would you be interested in that PR?

**Comment by rse** [comment]
IMHO it doesn't matter whether it is Browserify, Rollup, Webpack, Parcel or whatever else bundler. Because all bundlers cause some overhead when they expand the import/require structure and exactly this was it what causes the most overhead at the end. And I've now even already removed from the filesystem the splitted code base I had today, so I don't want to make a second attempt with just a different bundler. As I said, for me the now achieved reduction is in great balance to the fact that the entire Tokenizr API is still involved and ever other splitting would just bring back the additional burden of having to export and document different extension levels of the API.

**Comment by arackaf** [comment]
That's fair, at this point Rollup won't add much value since you've already inlined your library.

That said, for your future travels, Rollup is significantly better than Browserify. Assuming you use all ESM, and it seems you do, then Rollup's overhead is literally zero. It processes your imports and exports and literally just inlines everything. 

Thanks for all your amazing work!
